# Generated by Django 2.2.4 on 2019-09-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a_text',
            field=models.CharField(default='first', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='b_text',
            field=models.CharField(default='second', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='c_text',
            field=models.CharField(default='third', max_length=200),
            preserve_default=False,
        ),
    ]
