# Generated by Django 2.2.4 on 2019-09-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190908_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='b_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='c_text',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
