# Generated by Django 2.2.4 on 2019-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190908_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice_text',
            new_name='a_text',
        ),
        migrations.AddField(
            model_name='question',
            name='b_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='c_text',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
