# Generated by Django 2.2.4 on 2019-09-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190908_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='b_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='c_text',
        ),
    ]
